config_sim;

map_true = create_landmarks(map_radius, landmarks);
waypoint_list = create_waypoints(map_radius, waypoints);

[observations_1, odometry_1] = run_robot(map_true, waypoint_list, [0;0;0],...
    sensor_range, sensor_arc,...
    observation_noise, motion_noise, dt, max_v);
[observations_2, odometry_2] = run_robot(map_true, waypoint_list, [0;0;0],...
    sensor_range, sensor_arc,...
    observation_noise, motion_noise, dt, max_v);
[observations_3, odometry_3] = run_robot(map_true, waypoint_list, [0;0;0],...
    sensor_range, sensor_arc,...
    observation_noise, motion_noise, dt, max_v);
[observations_4, odometry_4] = run_robot(map_true, waypoint_list, [0;0;0],...
    sensor_range, sensor_arc,...
    observation_noise, motion_noise, dt, max_v);
[observations_5, odometry_5] = run_robot(map_true, waypoint_list, [0;0;0],...
    sensor_range, sensor_arc,...
    observation_noise, motion_noise, dt, max_v);