function [observations, odometry] = run_robot(map_true,...
    waypoint_list,...
    start_pose,...
    sensor_range,...
    sensor_arc,...
    observation_noise,...
    motion_noise,...
    dt,...
    max_v)

waypoints = length(waypoint_list);
pose = start_pose;
odometry = zeros(waypoints, 3);
time = 0;
observations = get_visible_landmarks(map_true, pose,...
    sensor_range,...
    sensor_arc,...
    observation_noise,...
    time); % t id x y

for ii = 1:waypoints
    wpt = waypoint_list(ii,2:3);
    while pdist([wpt;pose(1:2)'], 'euclidean') > close;
        delta_a = atan2(wpt(2) - pose(2), wpt(1) - pose(1)) - pose(3);
        if abs(delta_a) > 10 * eps
            u = [0 rotate(pose, wpt(1:2), dt)];
        else
            u = [velocity(pose(1:2)', wpt(1:2), max_v) 0]; 
        end
        time = time + dt;
        [odo, pose] = move_robot(pose, u, dt, motion_noise);
        obs = get_visible_landmarks(map_true, pose, sensor_range,...
                            sensor_arc, observation_noise, time);
        odometry(ii,:) = [time odo'];
        observations = [observations; obs];
    end
end