% mapFig = figure(1);
% axis([-map_radius map_radius -map_radius map_radius])
% axis square
% LG =  line('parent',gca,...
%     'linestyle','none',...
%     'marker','o',...
%     'color','r',...
%     'xdata',map_true(:,2),...
%     'ydata',map_true(:,3));

% WG =  line('parent',gca,...
%     'linestyle','none',...
%     'marker','x',...
%     'color','b',...
%     'xdata',waypoint_list(:,2),...
%     'ydata',waypoint_list(:,3));

% R =  line('parent',gca,...
%     'linestyle','none',...
%     'marker','+',...
%     'color','r',...
%     'xdata',[],...
%     'ydata',[]);
